#pragma once

#define PARAMETERPLUGIN_MAJOR 0
#define PARAMETERPLUGIN_MINOR 1
#define PARAMETERPLUGIN_PATCH 0
#define PARAMETERPLUGIN_VERSION ((PARAMETERPLUGIN_MAJOR << (8 * 3)) + (PARAMETERPLUGIN_MINOR << (8 * 2)) + (PARAMETERPLUGIN_PATCH << (8 * 1)))

#define _PARAMETERPLUGIN_VERSION_STR_TEXT(text) #text
#define _PARAMETERPLUGIN_VERSION_STR(major, minor, patch)                                                                     \
	_PARAMETERPLUGIN_VERSION_STR_TEXT(major) "." _PARAMETERPLUGIN_VERSION_STR_TEXT(minor) "." _PARAMETERPLUGIN_VERSION_STR_TEXT(patch)
#define PARAMETERPLUGIN_VERSION_STR _PARAMETERPLUGIN_VERSION_STR(PARAMETERPLUGIN_MAJOR, PARAMETERPLUGIN_MINOR, PARAMETERPLUGIN_PATCH)
